AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template for a production-ready MySQL RDS instance'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select a VPC for the RDS instance

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select at least two subnets in different Availability Zones in the selected VPC

  WebServerOneSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for the web server one EC2 instance

  WebServerTwoSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for the web server two EC2 instance

  DBInstanceIdentifier:
    Type: String
    Description: A name for the DB instance
    Default: mysqldb

  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    AllowedValues: 
      - db.t3.micro
      - db.t3.medium
      - db.t3.large
      - db.r5.large
      - db.r5.xlarge
    Description: The compute and memory capacity of the DB instance

  AllocatedStorage:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 65536
    Description: The allocated storage size in gigabytes (GB)

  MaxAllocatedStorage:
    Type: Number
    Default: 100
    Description: The upper limit in gigabytes (GB) to which Amazon RDS can automatically scale the storage

  BackupRetentionPeriod:
    Type: Number
    Default: 7
    MinValue: 0
    MaxValue: 35
    Description: The number of days for which automated backups are retained

  DatabaseName:
    Description: Latest EC2 Amazon Linux 2023 AMI from Systems Manager Parameter Store
    Type: String
    Default: 'mysqldb'


Resources:


############################################################################
# SECURITY LAYER 
############################################################################

  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS DB Instance
      SubnetIds: !Ref SubnetIds

  ##################
  # MySQL DB Security Group
  # Layer Type: Security Layer 
  # Description:
  ##################

  MySQLDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow only Web Server 1 and Web Server 2 to access database port 3306
      VpcId: 
        Ref: VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: 
            Ref: WebServerOneSecurityGroup
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: 
            Ref: WebServerTwoSecurityGroup
      Tags:
        - Key: Name
          Value: "MySQL DB Security Group"

############################################################################
# DATABASE LAYER 
############################################################################



  RDSInstanceParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: mysql8.0
      Description: Custom parameter group for MySQL 8.0
      Parameters:
        max_connections: 50
        slow_query_log: 1
        long_query_time: 2

  RDSInstanceSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Secrets for MySQL RDS instance made from cloudformation template
      Name: !Join ['-', [!Ref 'AWS::StackName', secret]]
      GenerateSecretString:
        SecretStringTemplate: '{"username": "dbdeveloper"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  RDSMySQLInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AvailabilityZone:  
         Fn::Select: 
           - 0
           - Fn::GetAZs: "" 
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref AllocatedStorage
      MaxAllocatedStorage: !Ref MaxAllocatedStorage
      Engine: MySQL
      EngineVersion: 8.0.39
      EnableCloudwatchLogsExports:
        - "error"
        - "general"
        - "slowquery"
        - "audit"
      EnableIAMDatabaseAuthentication: true
      MasterUsername: 
        !Join ['', ['{{resolve:secretsmanager:', !Ref RDSInstanceSecrets, ':SecretString:username}}' ]]
      MasterUserPassword: 
        !Join ['', ['{{resolve:secretsmanager:', !Ref RDSInstanceSecrets, ':SecretString:password}}' ]]
      DBName: 
        Ref: DatabaseName
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp3
      StorageEncrypted: true
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      VPCSecurityGroups: 
        - !Ref MySQLDBSecurityGroup
      DBParameterGroupName: !Ref RDSInstanceParameterGroup
      DeletionProtection: false
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

# Look into MonitoringInterval and MonitoringRoleArn
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html
        # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Monitoring.OS.html#USER_Monitoring.OS.Enabling

      


Outputs:
  RDSEndpoint:
    Description: Endpoint of the RDS instance
    Value: !GetAtt RDSMySQLInstance.Endpoint.Address

  RDSPort:
    Description: Port of the RDS instance
    Value: !GetAtt RDSMySQLInstance.Endpoint.Port

  MySQLDBSecurityGroupId:
    Description: ID of the security group for clients to use
    Value: !Ref MySQLDBSecurityGroup
  
  DBSecrets:
    Description: Secrets for RDS instance 
    Value: !Ref RDSInstanceSecrets