AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure setup

Parameters:
  VPCIdentifier:
    Type: String
    Description: VPC Identifier
    Default: '3114394F_VPC'

  LatestAL2023AmiId:
    Description: Latest EC2 Amazon Linux 2023 AMI from Systems Manager Parameter Store
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'

  VPCNetworkAddress:
    Type: String
    Description: asd
    Default: 10.0.0.0/16

  SubnetOneNetworkAddress:
    Type: String
    Description: Network Address for Subnet One
    Default: 10.0.1.0/24

  SubnetTwoNetworkAddress:
    Type: String
    Description: Network Address for Subnet Two
    Default: 10.0.2.0/24

  BackupSubnetOneNetworkAddress:
    Type: String
    Description: Network Address for Backup Subnet One
    Default: 10.0.3.0/24

  BackupSubnetTwoNetworkAddress:
    Type: String
    Description: Network Address for Backup Subnet Two
    Default: 10.0.4.0/24

  

Resources:

############################################################################
# NETWORK LAYER 
############################################################################

  ##################
  # ProductionVPC
  # Layer Type: Network Layer 
  # Description:
  ##################

  ProductionVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCNetworkAddress
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VPCIdentifier



  ##################
  # Production Subnet 1 
  # Layer Type: Network Layer 
  # Description:
  ##################

  ProductionVPCSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref SubnetOneNetworkAddress
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref ProductionVPC

  ##################
  # Production Subnet 2 
  # Layer Type: Network Layer 
  # Description:
  ##################
  ProductionVPCSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref SubnetTwoNetworkAddress
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref ProductionVPC


  ##################
  # Production Backup Subnet 1 
  # Layer Type: Network Layer 
  # Description:
  ##################

  ProductionVPCBackupSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref BackupSubnetOneNetworkAddress
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref ProductionVPC

  ##################
  # Production Subnet 2 
  # Layer Type: Network Layer 
  # Description:
  ##################
  ProductionVPCBackupSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref BackupSubnetTwoNetworkAddress
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref ProductionVPC


  ProductionVPCRoutingTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ProductionVPC


  #RouteOne:
  # Type: AWS::EC2::Route
  # Properties:
  #   RouteTableId: !Ref ProductionVPCRoutingTable
  #   GatewayId: !


  ##################
  # Subnet 1 ACL
  # Layer Type: Network Layer 
  # Description:
  ##################
  SubnetOneACL:
    Type: AWS::EC2::NetworkAcl
    Properties: 
      VpcId: !Ref ProductionVPC



  ##################
  # Subnet 2 ACL
  # Layer Type: Network Layer 
  # Description:
  ##################



  SubnetOneACLEntryOne:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: SubnetOneACL
      RuleNumber: 100
      RuleAction: allow

      CidrBlock: 172.16.0.0/24
      PortRange:
        From: 22
        To: 22

  SubnetOneACLEntryTwo:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: SubnetOneACL
      RuleNumber: 100
      Protocol: -1
      Egress: true
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      




############################################################################
# SECURITY LAYER 
############################################################################


  ##################
  # Web Server One Security Group
  # Layer Type: Network Layer 
  # Description:
  ##################
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: 
        Ref: ProductionVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ##################
  # Web Server Two Security Group
  # Layer Type: Network Layer 
  # Description:
  ##################

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: 
        Ref: ProductionVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

############################################################################
# COMPUTE LAYER 
############################################################################

  
  #AWS::EC2::Instance