AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure setup

Parameters:
  VPCIdentifier:
    Type: String
    Description: VPC Identifier
    Default: '3114394F_VPC'

  LatestAL2023AmiId:
    Description: Latest EC2 Amazon Linux 2023 AMI from Systems Manager Parameter Store
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'

  VPCNetworkAddress:
    Type: String
    Description: asd
    Default: 10.0.0.0/16

  SubnetOneNetworkAddress:
    Type: String
    Description: Network Address for Subnet One
    Default: 10.0.1.0/24

  SubnetTwoNetworkAddress:
    Type: String
    Description: Network Address for Subnet Two
    Default: 10.0.2.0/24

  BackupSubnetOneNetworkAddress:
    Type: String
    Description: Network Address for Backup Subnet One
    Default: 10.0.3.0/24

  BackupSubnetTwoNetworkAddress:
    Type: String
    Description: Network Address for Backup Subnet Two
    Default: 10.0.4.0/24

  

Resources:

############################################################################
# NETWORK LAYER 
############################################################################

  ##################
  # ProductionVPC
  # Layer Type: Network Layer 
  # Description:
  ##################

  ProductionVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCNetworkAddress
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VPCIdentifier



  ##################
  # Production Subnet 1 
  # Layer Type: Network Layer 
  # Description:
  ##################

  ProductionVPCSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref SubnetOneNetworkAddress
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      VpcId: !Ref ProductionVPC

  ##################
  # Production Subnet 2 
  # Layer Type: Network Layer 
  # Description:
  ##################
  ProductionVPCSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref SubnetTwoNetworkAddress
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: false
      VpcId: !Ref ProductionVPC


  ##################
  # Production Backup Subnet 1 
  # Layer Type: Network Layer 
  # Description:
  ##################

  ProductionVPCBackupSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref BackupSubnetOneNetworkAddress
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref ProductionVPC

  ##################
  # Production Subnet 2 
  # Layer Type: Network Layer 
  # Description:
  ##################
  ProductionVPCBackupSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref BackupSubnetTwoNetworkAddress
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref ProductionVPC

############################################################################
##  PRODUCTION VPC ROUTING TABLE CONFIGURATION
############################################################################

  SubnetOneRoutingTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ProductionVPC
      Tags:
        - Key: Name
          Value: "Production VPC Routing Table"


  SubnetOneRoutingTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: 
        Ref: SubnetOneRoutingTable
      SubnetId:
        Ref: ProductionVPCSubnetOne

  SubnetTwoRoutingTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: 
        Ref: SubnetOneRoutingTable
      SubnetId: 
        Ref: ProductionVPCSubnetTwo

  #RouteOne:
  # Type: AWS::EC2::Route
  # Properties:
  #   RouteTableId: !Ref ProductionVPCRoutingTable
  #   GatewayId: !


############################################################################
##  BACKUP SUBNET ROUTING TABLE CONFIGURATION
############################################################################

  SubnetTwoRoutingTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ProductionVPC
      Tags:
        - Key: Name
          Value: "Private Subnet Routing Table"


############################################################################
##  SUBNET ONE ACCESS CONTROL LIST CONFIGURATION
############################################################################


  ##################
  # Subnet 1 ACL
  # Layer Type: Network Layer 
  # Description:
  ##################
  SubnetOneACL:
    Type: AWS::EC2::NetworkAcl
    Properties: 
      VpcId: 
        Ref: ProductionVPC
      Tags:
        - Key: Name
          Value: "Subnet One ACL"

  ##################
  # Subnet 1 ACL Association
  # Layer Type: Network Layer 
  # Description: Associate ACL to Subnet One
  ##################
  SubnetOneACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: 
        Ref: SubnetOneACL
      SubnetId: 
        Ref: ProductionVPCSubnetOne

  
  SubnetOneACLEntryOne:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: SubnetOneACL
      RuleNumber: 100
      RuleAction: allow
      Protocol: 6
      CidrBlock: 172.16.0.0/24
      PortRange:
        From: 22
        To: 22

  SubnetOneACLEntryTwo:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: SubnetOneACL
      RuleNumber: 100
      Protocol: -1
      Egress: true
      RuleAction: allow
      CidrBlock: 0.0.0.0/0

############################################################################
##  SUBNET TWO ACCESS CONTROL LIST CONFIGURATION
############################################################################

  ##################
  # Subnet 2 ACL
  # Layer Type: Network Layer 
  # Description:
  ##################
  SubnetTwoACL:
    Type: AWS::EC2::NetworkAcl
    Properties: 
      VpcId: 
        Ref: ProductionVPC
      Tags:
        - Key: Name
          Value: "Subnet Two ACL"


  ##################
  # Subnet 2 ACL Association
  # Layer Type: Network Layer 
  # Description: Associate ACL to Subnet One
  ##################
  SubnetTwoACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: 
        Ref: SubnetTwoACL
      SubnetId: 
        Ref: ProductionVPCSubnetTwo

############################################################################
##  INTERNET GATEWAY
############################################################################     
    
  ProductionVPCInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags:
        - Key: "Name"
          Value: "Production VPC Internet Gateway"



############################################################################
# SECURITY LAYER 
############################################################################


  ##################
  # Web Server One Security Group
  # Layer Type: Security Layer 
  # Description:
  ##################
  WebServerOneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Internet users to access HTTP (Port 80)
      VpcId: 
        Ref: ProductionVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: "Web Server One Security Group"

  ##################
  # Web Server Two Security Group
  # Layer Type: Security Layer 
  # Description:
  ##################

  WebServerTwoSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Internet Users to access SSH (Port 22)
      VpcId: 
        Ref: ProductionVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: "Web Server Two Security Group"


  ##################
  # MySQL DB Security Group
  # Layer Type: Security Layer 
  # Description:
  ##################

  MySQLDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow only Web Server 1 and Web Server 2 to access database port 3306
      VpcId: 
        Ref: ProductionVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 
            Fn::GetAtt: [ProductionVPCSubnetOne, CidrBlock]
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 
            Fn::GetAtt: [ProductionVPCSubnetTwo, CidrBlock]
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 
            Fn::GetAtt: [ProductionVPCSubnetOne, CidrBlock]
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 
            Fn::GetAtt: [ProductionVPCSubnetTwo, CidrBlock]
      Tags:
        - Key: Name
          Value: "MySQL DB Security Group"


############################################################################
## KEY PAIR (SECURITY LAYER)
############################################################################

  WebServerOneKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: WebServerOneKeyPair

  WebServerTwoKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: WebServerTwoKeyPair



############################################################################
# COMPUTE LAYER 
############################################################################


# Refer to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance-launchtemplatespecification.html

  #WebServerLaunchTemplate:
  #  Type: AWS::EC2::LaunchTemplate
  #  Properties:
  #    LaunchTemplateData: #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html
  #    LaunchTemplateName: String
  #    TagSpecifications: #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatetagspecification.html
  #    VersionDescription: String


# Refer https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance-launchtemplatespecification.html
  # WebServerLaunchTemplateSpecification:
    #   LaunchTemplateId: String
    #  LaunchTemplateName: String
    #  Version: String


  
  ##################
  # Web Server One EC2
  # Layer Type: Compute Layer 
  # Description:
  ##################     
  #WebServerOne:
  #  Type: AWS::EC2::Instance
    #Properties:
    #  InstanceType: t2.micro
    #  LaunchTemplate: 
        #Ref: WebServerLaunchTemplateSpecification
    # ImageId: 
      # Ref: LatestAL2023AmiId
    # KeyName:
      # Ref: WebServerOneKeyPair
    # SecurityGroupIds: 
      #Ref: WebServerOneSecurityGroup
    # SubnetId: 
      # Ref: ProductionVPCSubnetOne
    # Tags:
      # - Key: "Name"
          #Value: Web Server One



  ##################
  # Web Server Two EC2
  # Layer Type: Compute Layer 
  # Description:
  ##################

  #WebServerTwo:
  #  Type: AWS::EC2::Instance
    #Properties:
    #  InstanceType: t2.micro
    #  LaunchTemplate:
      # Ref: WebServerLaunchTemplateSpecification
    # ImageId: 
      # Ref: LatestAL2023AmiId
    # KeyName:
      # Ref: WebServerTwoKeyPair
    # SecurityGroupIds: 
      #Ref: WebServerTwoSecurityGroup
    # SubnetId: 
      # Ref: ProductionVPCSubnetTwo
    # Tags:
      # - Key: "Name"
          #Value: Web Server Two



############################################################################
# DATABASE LAYER 
############################################################################

  ##################
  # MYSQL Database
  # Layer Type: Database Layer 
  # Description:
  ##################

